from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os
from datetime import datetime

class AuditReportGenerator:
    def __init__(self):
        pass

    def generate_report(self, output_path, data, insights):
        doc = Document()
        
        # --- COVER PAGE ---
        self._add_cover_page(doc, data)
        
        # --- EXECUTIVE SUMMARY ---
        doc.add_page_break()
        self._add_heading(doc, "1.0 EXECUTIVE SUMMARY", level=1)
        doc.add_paragraph(insights.get("executive_summary", "No summary available."))
        
        # --- FINANCIAL & PROGRESS AUDIT ---
        self._add_heading(doc, "2.0 FINANCIAL & PROGRESS AUDIT", level=1)
        
        # Create a table for financial metrics
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Metric'
        hdr_cells[1].text = 'Value'
        
        # Add some metrics from the last trend point
        last_trend = data[-1] if data else {}
        metrics = [
            ("Time Elapsed", f"{last_trend.get('time_progress', '0')}%"),
            ("Financial Progress", f"{last_trend.get('financial_progress', '0')}%"),
            ("Slippage / Variance", f"{self._calculate_slippage(last_trend)}%"),
            ("Risk Verdict", insights.get("claim_verdict", "Unknown"))
        ]
        
        for metric, value in metrics:
            row_cells = table.add_row().cells
            row_cells[0].text = metric
            row_cells[1].text = value
            
        doc.add_paragraph("\nCritical Advice:")
        doc.add_paragraph(insights.get("critical_advice", "No critical advice available."), style='List Bullet')

        # --- SWOT ANALYSIS ---
        doc.add_page_break()
        self._add_heading(doc, "3.0 SWOT INTELLIGENCE", level=1)
        
        swot = insights.get("swot", {})
        sections = [
            ("STRENGTHS", swot.get("strengths", []), "008000"), # Green
            ("WEAKNESSES", swot.get("weaknesses", []), "FF0000"), # Red
            ("OPPORTUNITIES", swot.get("opportunities", []), "FFA500"), # Orange
            ("THREATS", swot.get("threats", []), "0000FF") # Blue
        ]
        
        for title, items, color in sections:
            p = doc.add_paragraph()
            run = p.add_run(title)
            run.bold = True
            run.font.color.rgb = RGBColor.from_string(color)
            
            if not items:
                doc.add_paragraph("No items identified.")
            else:
                for item in items:
                    doc.add_paragraph(item, style='List Bullet')
            doc.add_paragraph("")

        # --- STAKEHOLDER RECOMMENDATIONS ---
        doc.add_page_break()
        self._add_heading(doc, "4.0 STRATEGIC RECOMMENDATIONS", level=1)
        
        recs = insights.get("recommendations", {})
        
        self._add_heading(doc, "4.1 TO THE CLIENT (PM)", level=2)
        for item in recs.get("to_client", ["No recommendations available."]):
            doc.add_paragraph(item, style='List Bullet')
            
        self._add_heading(doc, "4.2 TO THE CONTRACTOR", level=2)
        for item in recs.get("to_contractor", ["No recommendations available."]):
            doc.add_paragraph(item, style='List Bullet')

        # --- CLOSING ---
        doc.add_paragraph("\n\nReport generated by Construction Aggregator.")
        doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        doc.save(output_path)
        return output_path

    def _add_cover_page(self, doc, data):
        # Center alignment for cover
        for i in range(10): doc.add_paragraph() # Spacer
        
        title = doc.add_paragraph("PROJECT AUDIT & RISK INTELLIGENCE REPORT")
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.runs[0]
        run.bold = True
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(47, 84, 150) # Dark Blue
        
        subtitle = doc.add_paragraph("Tactical Site Performance Analysis")
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(14)
        
        for i in range(5): doc.add_paragraph() # Spacer
        
        info = doc.add_paragraph(f"Generated for: Makindu Affordable Housing Project")
        info.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        date_para = doc.add_paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y')}")
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    def _add_heading(self, doc, text, level=1):
        h = doc.add_heading(text, level=level)
        # Custom styling could be added here

    def _calculate_slippage(self, trend):
        try:
            time = float(trend.get('time_progress', 0))
            work = float(trend.get('financial_progress', 0))
            return round(time - work, 2)
        except:
            return 0
